### ISSUE TITLE
apodo compatible with connexion

### ISSUE THREAD

**Issue by sharkguto** [elliott-maguire/apodo#26]
Hi elliott,

Do you have any plan to implement a blueprint layer like https://github.com/zalando/connexion, for your framework?

It would be great to have a layer like connexion, that we write first the openapi documentation and use it for the routes.

If yes, how can I help you ?

Let's try to revive vibora :rocket: :1st_place_medal: :tada:

**Comment by glotchimo** [comment]
Hey there! I am currently in the process of re-implementing a bare-bones version of the core server, including a blueprint mechanic. We're trying to keep things as closely-knit as possible to retain efficiency and speed, as well as strong system design.

Check out the `rebuild-server` branch to see where I'm at. It should only be another day or two for me to nail down the finishing touches, and then we'll hit the ground running with more features. If you aren't already in it, hop into the [Slack channel](https://join.slack.com/t/apodo/shared_invite/enQtNzMxODE4Njk2OTk0LWE0MDA3N2I2MDEyZmQxMGQzYzhmZDZiZmQwYzRjNjYzNGY3OGJkNjI5MWJlMzQyZWVmY2I3M2Q4NTg2MzA1ODQ) to keep up-to-date.
