### ISSUE TITLE
ASGI or WSGI

### ISSUE THREAD

**Issue by blueray453** [elliott-maguire/apodo#28]
I mainly got interested in Vibora because of the ease of deployment. Then I found out that Vibora is probably dead and Apodo is the fork of Vibora.

I do not want to worry about Apache, Nginx, Gunicorn, Daphne, Uvicorn, Hypercorn etc. In this age of DevOps, Agile, Serverless, Continuous Deployment - I am not sure how relevant these words are to the developers.

Golang standard library has very good support for server. Go people seems to neither like server nor frameworks. They do not have the concept of WSGI or ASGI. They do not need it. They seems to be very content with the standard library.

On the other hand, if we want to use Python for web development, we have to use a framework and some extra stuff to deploy. We do not find it interesting or useful to learn and use those stuff.

I think the focus and selling point of this project should be the Built in Deployment Server and Ease of Deployment. Developers should not even worrying about zero downtime deployment strategies. Server config should be used for blue/green or rolling deployment. And as mentioned in https://youtu.be/hulRKdSPUOc?t=15m10s backward compatibility and application specific issues should be addressed by the framework.

Even better, if we can come up with a production server (from now on I will call it Apodo-Server) that all python frameworks, or vanilla python developers can use. For, example Django/Flask will replace their development server with Apodo-Server and thus will no longer need Nginx and Gunicorn.

This server will be default to Apodo. The idea is, If you use Apodo framework with Apodo-Server then you get fast, easy, zero downtime deployment support for both server and the application.

The only reason why i was ferreting around these plethora of python frameworks and ended up here is ease of deployment. Please, let's have a discussion. Let's discuss about this idea. Let's see where it leads us. I can not foresee anything other than greatness.

**Comment by glotchimo** [comment]
I love it! A lot of this aligns with my vision for the project. What we wanted to achieve early on was development of modular components, similar to what you were talking about with Apodo-Server and Apodo, the framework.

I'd love for you to join us in the Slack channel so you can give your input. We're still very early on, and since the team is small, it's slow because we're all very busy, but we're all still very excited about the project!

**Comment by blueray453** [comment]
I joined slack yesterday. I am reading all three channels and trying to figure out where I will fit in.

**Comment by prostomarkeloff** [comment]
I very like this idea. We should create a very hackable and customizable web-server with related python web-framework.
