### ISSUE TITLE
Port components

### ISSUE THREAD

**Issue by glotchimo** [elliott-maguire/apodo#7]
The `legacy.components` module needs to be ported from legacy to Gato.

The majority of changes will consist of an increase of commenting and changes in formatting. There will also be some minor syntax changes to more favorable patterns.

**Comment by elliott-maguire** [comment]
Note that the `Component` class needs to subclass `object` in order for the usage of `__slots__` to be effective to any degree.

**Comment by glotchimo** [comment]
Implemented in #21
